name: Vakudator-CI
on:
  push:
     branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  java-project-78:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/app

    steps:
      - name: Test Workflow
        run: echo "Hello World"
