name: Vakudator-CI
on:
  push:
     branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  java-project-78:
    runs-on: ubuntu-latest

    steps:
      - name: Test Workflow
        run: echo "Hello World"
        
      - name: Checkout code
        uses: actions/checkout@v4.2.1
